services:
#  db:
#    image: postgres:14-alpine
#    container_name: inventory_db
#    restart: unless-stopped
#    environment:
#      POSTGRES_DB: ${DB_NAME}
#      POSTGRES_USER: ${DB_USER}
#      POSTGRES_PASSWORD: ${DB_PASSWORD}
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
#    env_file:
#      - .env

  redis:
    image: redis:7-alpine
    container_name: inventory_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data


  web:
    build: .
    container_name: inventory_web
    restart: unless-stopped
    command: ["./entrypoint.sh", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
#      - db
      - redis
    env_file:
      - .env

  bot:
    build: .
    container_name: inventory_bot
    restart: unless-stopped
    command: ["./entrypoint.sh", "python", "manage.py", "runbot"]
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
#      - db
#      - web
      - redis
    env_file:
      - .env

  celery:
    build: .
    container_name: inventory_celery
    restart: unless-stopped
    command: ["celery", "-A", "config", "worker", "--loglevel=info"]
    volumes:
      - .:/app
      - media_volume:/app/media
    depends_on:
      - redis
#      - db
    env_file:
      - .env

volumes:
#  postgres_data:
  static_volume:
  media_volume:
  redis_data: